### ISSUE TITLE
Add svn update

### ISSUE THREAD

**Issue by mholo65** [cake-contrib/Cake.Svn#9]
Add support for `svn update` command

**Comment by DaisyDave** [comment]
I have almost completed the implementation of this feature but need some advice to get round the (hopefully) final problem. The DupFinder is failing my build because the first 6 lines of SvnCheckoutSettingsExtensions.ToSharpSvn() matches the first 6 lines in my new SvnUpdateSettingsExtensions.ToSvnUpdateArgs().

Can you suggest how I disable this check? Or work round the issue.

The actual error message is:
`Duplicate Located with a cost of 86, across 2 Fragments
File Name: src\Cake.Svn\Checkout\SvnCheckoutSettingsExtensions.cs Line Numbers: 11 - 22
File Name: src\Cake.Svn\Update\SvnUpdateSettingsExtensions.cs Line Numbers: 15 - 26
An error occurred when executing task 'DupFinder'.`
